name = "siteredirects"
main = "worker.js"
compatibility_date = "2025-08-21"
preview_urls = false
send_metrics = false
workers_dev = false


# If you are manually editing setting up this project,
# then make sure to uncomment and change the routes below to the domain that you own.

#routes = [
#  { "pattern": "mydomain.com", "custom_domain": true},
#  { "pattern": "www.mydomain.com","custom_domain": true }
#]

[[kv_namespaces]]
binding = "REDIRECTS"
id = ""

# For developing on linux in testing.
[dev]
ip = "127.0.0.1"

[vars]
# where / should navigate to this should always be filled out.
# EX: FALLBACK_URL = "https://www.twitch.tv/socksthewolf"
FALLBACK_URL = ""